config/routes.rb
Rails.application.routes.draw do

 

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  devise_for :admins
  resources :users
  resources :searches
  post '/rate' => 'rater#create', :as => 'rate'
 resources :administrations

 root :to => "home#index"

  resources :urednicis do
    resources :reviews, except: [:show, :index]
  end
 

 resources :reviews do

  get :confirm, on: :member

 end

 

end

app/models/urednici.rb
class Urednici < ActiveRecord::Base

	ratyrate_rateable "Ochota", "Spolehlivost", "Zkušenosti"

	has_many :reviews

	#searchkick




def self.search(search)
  if search
    self.where("name like ?", "%#{search}%")
  else
    self.all
  end
end


end

app/controllers/urednicis_controller.rb
class UrednicisController < ApplicationController
  before_action :set_urednici, only: [:show, :edit, :update, :destroy]
  

  # GET /urednicis
  # GET /urednicis.json
  #def index
  #  @urednicis = Urednici.all
    #@urednicis = Urednici.search(params[:search])
 # end

  

def index
  @urednicis = Urednici.search(params[:search])
end


# @urednicis = Urednici.search(params[:search])  index
   #@urednicis = Urednici.all


#def search
#    if params[:search].present?
#      @urednicis = Urednici.search(params[:search])
#    else
#      @urednicis = Urednici.all
#    end
#  end


#def search
#@search = Urednici.search(params[:q])
#@urednici = @search.result
#end


  def show

    #@review = Review.where(urednici_id: @urednici.id).order("created_at DESC")


    @avg_review = @urednici.reviews.average(:rating).to_f.round(2)
  
end
 


  # GET /urednicis/new
  def new
    @urednici = Urednici.new
  end

  # GET /urednicis/1/edit
  def edit
  end

  # POST /urednicis
  # POST /urednicis.json
  def create
    @urednici = Urednici.new(urednici_params)

    respond_to do |format|
      if @urednici.save
        format.html { redirect_to @urednici, notice: 'Úředník byl úspěšně přidán' }
        format.json { render :show, status: :created, location: @urednici }
      else
        format.html { render :new }
        format.json { render json: @urednici.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urednicis/1
  # PATCH/PUT /urednicis/1.json
  def update
    respond_to do |format|
      if @urednici.update(urednici_params)
        format.html { redirect_to @urednici, notice: 'Úředník byl úspěšně aktualizován' }
        format.json { render :show, status: :ok, location: @urednici }
      else
        format.html { render :edit }
        format.json { render json: @urednici.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urednicis/1
  # DELETE /urednicis/1.json
  def destroy
    @urednici.destroy
    respond_to do |format|
      format.html { redirect_to urednicis_url, notice: 'Úředník byl úspěšně smazán' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_urednici
      @urednici = Urednici.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def urednici_params
      params.require(:urednici).permit(:name, :surname, :street, :city, :zip)
    end
end

app/helpers/urednicis_helper.rb
module UrednicisHelper
end

app/views/urednicis/_form.html.erb
<%= form_for(@urednici) do |f| %>
  <% if @urednici.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@urednici.errors.count, "error") %> prohibited this urednici from being saved:</h2>

      <ul>
      <% @urednici.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Jméno %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Příjmení %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :Ulice %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :Město %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :PSČ %><br>
    <%= f.number_field :zip %>
  </div>
  
<div><%= f.submit "Potvrďit", class: "button" %></div>


<% end %>

app/views/urednicis/edit.html.erb
<h1>Editace úředníka</h1>

<%= render 'form' %>

<%= link_to 'Detail', @urednici %> |
<%= link_to 'Zpět', urednicis_path %>

app/views/urednicis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seznam úředníků</h1>

<table>
  <thead>
    <tr>
      <th>Jméno</th>
      <th>Příjmení</th>
      <th>Ulice</th>
      <th>Město</th>
      <th>PSČ</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @urednicis.each do |urednici| %>
      <tr>
        <td><%= urednici.name %></td>
        <td><%= urednici.surname %></td>
        <td><%= urednici.street %></td>
        <td><%= urednici.city %></td>
        <td><%= urednici.zip %></td>

        <% if admin_signed_in? %>  


        <td><%= link_to 'Detail', urednici %></td>
        <td><%= link_to 'Editovat', edit_urednici_path(urednici) %></td>
        <td><%= link_to 'Smazat', urednici, method: :delete, data: { confirm: 'Jste si jisti?' } %></td>

        

        <%else%>

        <td><%= link_to 'Detail', urednici %></td>

          <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>


<% if admin_signed_in? %>  

<%= link_to 'Přidat nového úředníka', new_urednici_path %>

<% end %>

app/views/urednicis/new.html.erb
<h1>Přidání nového úředníka</h1>

<%= render 'form' %>

<%= link_to 'Zpět', urednicis_path %>

app/views/urednicis/show.html.erb
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <div class="small-5 columns">

            <div class="table-responsive">
              <table class="table">
               <tbody>

    <tr>
      <td><strong>Jméno:</strong></td>
      <td><%= @urednici.name %></td>
    </tr>
 
    <tr>
      <td><strong>Příjmení:</strong></td>
      <td><%= @urednici.surname %></td>
    </tr>
 
    <tr>
      <td><strong>Ulice:</strong></td>
      <td><%= @urednici.street %></td>
    </tr>
 
    <tr>
      <td><strong>Město:</strong></td>
      <td><%= @urednici.city %></td>
    </tr>
 
    <tr>
      <td><strong>PSČ:</strong></td>
      <td><%= @urednici.zip %></td>
    </tr>
    
   </tbody>
  </table>




      <strong>Celkové hodnocení:</strong>
    
<br>
 

        <div class="star-rating" data-score= <%= @avg_review %> ></div>
        <em><%= "#{@urednici.reviews.count} Hodnocení" %></em>


<br><br>

     
      <strong>Oznámkuj zvlášť vlastnosti jako ve škole:</strong>
    

<br>
 

Ochota  : <%= rating_for @urednici, "Ochota", :star => 5, :disable_after_rate => false, :enable_half => true, :half_show => true, :cancel_hint => "Zrušit hodnocení!"  %>
Spolehlivost : <%= rating_for @urednici, "Spolehlivost", :star => 5, :disable_after_rate => false, :enable_half => true, :half_show => true, :cancel_hint => "Zrušit hodnocení!" %>
Zkušenosti  : <%= rating_for @urednici, "Zkušenosti", :star => 5, :disable_after_rate => false, :enable_half => true, :half_show => true, :cancel_hint => "Zrušit hodnocení!" %>
 


<br>

  <%= link_to "Napsat nové hodnocení", new_urednici_review_path(@urednici) %>
        </div>
        </div>
 




<div class="large-7 columns">
        <h1 class="review_title"><%= @urednici.name %></h1>
       
        <% if @urednici.reviews.confirmed.empty? %>
          <h3>Zatím zde nejsou žádné hodnocení, chceš být první? </h3>
          <%= link_to "Napsat hodnocení", new_urednici_review_path(@urednici), class: "btn btn-danger" %>
        <% else %>

          <% @urednici.reviews.confirmed.each do |review| %>
            <div class="reviews">
              <div class="star-rating" data-score= <%= review.rating %> ></div>
              
             
              <p><%= review.comment %></p>

              <p>autor hodnocení: <%= review.user.username %> </p>


            


            </div>
          <% end %>
        <% end %>
        <ul class="pagination">
  <li class="arrow unavailable"><a href="">&laquo;</a></li>
  <li class="current"><a href="">1</a></li>
  <li><a href="">2</a></li>
  <li><a href="">3</a></li>
  <li><a href="">4</a></li>
  <li class="unavailable"><a href="">&hellip;</a></li>
  <li><a href="">12</a></li>
  <li><a href="">13</a></li>
  <li class="arrow"><a href="">&raquo;</a></li>
</ul>

      </div>
    </div>
  </div>
</div>



<br>
<%= link_to 'Editovat', edit_urednici_path(@urednici) %> |
<%= link_to 'Zpět', urednicis_path %>


<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>