config/routes.rb
Rails.application.routes.draw do

 

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  devise_for :admins
  resources :users
  resources :searches
  post '/rate' => 'rater#create', :as => 'rate'
 resources :administrations

 root :to => "home#index"

  resources :urednicis do
    resources :reviews, except: [:show, :index]
  end
 

 resources :reviews do

  get :confirm, on: :member

 end

 

end

app/controllers/administrations_controller.rb
class AdministrationsController < ApplicationController

before_action :set_review, only: [:show]


	def index

	@reviews = Review.where(confirmed:false)

	end




private

	def set_review
      @review = Review.find(params[:id])
    end


    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/administration_helper.rb
module AdministrationHelper
end

app/views/administrations/index.html.erb
<h1>Administrace</h1>


   <% @reviews.each do |review| %>
            <div class="reviews">
              <div class="star-rating" data-score= <%= review.rating %> ></div>
              
             
              <p><%= review.comment %></p>

              <p>autor hodnocení: <%= review.user.username %> </p>

<%= link_to 'Schválit', confirm_review_path(review) %> |
<%= link_to 'Smazat', review_path(review) , method: :delete%>
            


            </div>
          <% end %>


          <script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>