config/routes.rb
Rails.application.routes.draw do

 

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  devise_for :admins
  resources :users
  resources :searches
  post '/rate' => 'rater#create', :as => 'rate'
 resources :administrations

 root :to => "home#index"

  resources :urednicis do
    resources :reviews, except: [:show, :index]
  end
 

 resources :reviews do

  get :confirm, on: :member

 end

 

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy, :confirm]
  before_action :set_urednici, except: [:confirm, :destroy]
  before_action :authenticate_user!, except: [:confirm, :destroy]
  before_action :authenticate_admin!, only: [:confirm, :destroy]


  def new
    @review = Review.new
  end


  def edit
  end


  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.urednici_id = @urednici.id

      if @review.save
        redirect_to @urednici
      else
        render 'new'
    end
  end

    def update
      @review.update(review_params)
    end


 def destroy
      @review.destroy
      redirect_to administrations_path
    end


  def confirm

    @review.confirmed = true
    @review.save
    redirect_to administrations_path

  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_review
      @review = Review.find(params[:id])
    end

    def set_urednici
      @urednici = Urednici.find(params[:urednici_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end


end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@urednici, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="field">
  <div id="star-rating"></div>
  </div>
  

  <div class="field">
    <%= f.label :Hodnocení %><br>
    <%= f.text_area :comment %>
  </div>

  
 <div><%= f.submit "Potvrďit", class: "button" %></div>


<% end %>


<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Úprava hodnocení</h1>

<%= render 'form' %>

<%= link_to 'Zpátky', urednici_path(@urednici)%>

app/views/reviews/new.html.erb
<h1>Nové hodnocení</h1>

<%= render 'form' %>

<%= link_to 'Zpátky', urednici_path(@urednici)%>