config/routes.rb
Rails.application.routes.draw do

 

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  devise_for :admins
  resources :users
  resources :searches
  post '/rate' => 'rater#create', :as => 'rate'
 resources :administrations

 root :to => "home#index"

  resources :urednicis do
    resources :reviews, except: [:show, :index]
  end
 

 resources :reviews do

  get :confirm, on: :member

 end

 

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :timeoutable # :lockable#, :confirmable 
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :user
	belongs_to :urednici

	scope :confirmed, -> {where(confirmed: true)}
end

app/models/urednici.rb
class Urednici < ActiveRecord::Base

	ratyrate_rateable "Ochota", "Spolehlivost", "Zkušenosti"

	has_many :reviews

	#searchkick




def self.search(search)
  if search
    self.where("name like ?", "%#{search}%")
  else
    self.all
  end
end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable, :confirmable and :activatable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  ratyrate_rater

  has_many :reviews, dependent: :destroy
  #devise_for :users, controllers: { sessions: "users/sessions" }
#attr_accessible :email, :password, :password_confirmation, :remember_me, :encrypted_password
  #before_action :authenticate_user!
#User.new.respond_to?(:encrypted_password=) => false

#devise_scope :user do
  #get "sign_in", to: "devise/sessions#new"
#end
  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


def index

end


end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy, :confirm]
  before_action :set_urednici, except: [:confirm, :destroy]
  before_action :authenticate_user!, except: [:confirm, :destroy]
  before_action :authenticate_admin!, only: [:confirm, :destroy]


  def new
    @review = Review.new
  end


  def edit
  end


  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.urednici_id = @urednici.id

      if @review.save
        redirect_to @urednici
      else
        render 'new'
    end
  end

    def update
      @review.update(review_params)
    end


 def destroy
      @review.destroy
      redirect_to administrations_path
    end


  def confirm

    @review.confirmed = true
    @review.save
    redirect_to administrations_path

  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_review
      @review = Review.find(params[:id])
    end

    def set_urednici
      @urednici = Urednici.find(params[:urednici_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def new 

		@search = Search.new
	end


	def create

		@search = Search.create!(params[:search])
		redirect_to @search
	end

	def show

		@search = Search.find(params[:id])
	end

	def index
		@search = Urednici.ransack(params[:q])
		@urednicis = @search.result
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  
  @reviews = @user.reviews
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :surname, :email, :username)
    end
end

app/helpers/administration_helper.rb
module AdministrationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/urednicis_helper.rb
module UrednicisHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/users_page_helper.rb
module UsersPageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Databáze známých úředníků" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
 <body>
    <div class="row">
      <nav class="top-bar column" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1>
              <a href="/">
               Úředníci
              </a>
            </h1>
          </li>
           <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar"><a href="#"><span>Menu</span></a></li>
        </ul>



        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">

            <%if user_signed_in?%>
              <li><%=link_to current_user.email, edit_user_registration_path%></li>
              <li><%=link_to "Odhlásit", destroy_user_session_path, method: :delete%></li>
               <li><%=link_to "Seznam úředníků", urednicis_path%></li>
               <li><%=link_to "Můj účet", user_path(current_user)%></li>
           

            <%end%>

              <%if admin_signed_in?%>
              <li><%=link_to current_admin.email%></li>
              <li><%=link_to "Odhlásit", destroy_admin_session_path, method: :delete%></li>
               <li><%=link_to "Seznam úředníků", urednicis_path%></li>
               <li><%=link_to "Administrace", administrations_path%></li>

                <%end%>
               
            <%if !user_signed_in? && !admin_signed_in? %>
              <li><%=link_to "Registrovat", new_user_registration_path%></li>
              <li><%=link_to "Přihlásit se", new_user_session_path%></li>
              <li><%=link_to "Seznam úředníků", urednicis_path%></li>
          <%end%>



          </ul>

          <!-- Left Nav Section -->


               
             

          <ul class="left">
            <li class="has-form">
              <div class="row collapse">
               
              <div class="large-5 small-9 columns">

                  <%= form_tag urednicis_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
                  <p><%= text_field_tag :search, params[:search], class: "radius-left expand", placeholder: "Najít úředníka" %></p>  

              </div>


              <div class="large-4 small-3 columns">
                  
                    <p><%= submit_tag "Hledat", name: nil, class: "radius-right button" %></p>

                    <% end %>            

              </div>

              <div class="small-3 columns">

                    <p><%=link_to "Rozšířené vyhledávání", searches_path%></p>

               </div>

               
              </div>
            </li>
          </ul>
        </section>
      </nav>
    </div>




  
    <div id="main-content" class="row full-min-height">
      <%= yield %>
    </div>

    <footer class="row">
      <div class="large-12 columns">
        <hr>
        <p>© Úředníci 2015</p>
      </div>
    </footer>

    <%= javascript_include_tag "application" %>

  </body>
</html>